services:

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    restart: always
    build: ./backend
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build: ./frontend
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "8080:8501"

    depends_on:
      - backend

volumes:
  mysql_data:
